# Creates a production upload keystore for Google Play Store signing and appends entries to local.properties.
param(
    [string]$StorePassword = "InvoiceHammerUpload2026",
    [string]$KeyPassword = "InvoiceHammerUpload2026",
    [string]$Alias = "upload"
)

$ErrorActionPreference = "Stop"
$root = Split-Path -Parent $PSScriptRoot
$keystoreDir = Join-Path $root "keystore"
$keystoreFile = Join-Path $keystoreDir "invoicehammer-upload.jks"
$localProps = Join-Path $root "local.properties"

New-Item -ItemType Directory -Force -Path $keystoreDir | Out-Null

if (Test-Path $keystoreFile) {
    Write-Host "Keystore already exists: $keystoreFile"
} else {
    $keytool = Join-Path $env:JAVA_HOME "bin\keytool.exe"
    if (-not (Test-Path $keytool)) {
        $keytool = "C:\Program Files\Android\Android Studio\jbr\bin\keytool.exe"
    }
    if (-not (Test-Path $keytool)) {
        $keytool = "keytool.exe" # Fallback to path
    }

    & $keytool -genkeypair -v `
        -keystore $keystoreFile `
        -alias $Alias `
        -keyalg RSA -keysize 2048 -validity 10000 `
        -storepass $StorePassword -keypass $KeyPassword `
        -dname "CN=Invoice Hammer Upload, OU=Mobile, O=Fordham, L=Local, ST=NA, C=US"

    Write-Host "Created upload keystore: $keystoreFile"
}

$relativeStore = "keystore/invoicehammer-upload.jks"
$lines = @(
    "",
    "# Production release signing (auto-generated by create-upload-keystore.ps1)",
    "release.storeFile=$relativeStore",
    "release.storePassword=$StorePassword",
    "release.keyAlias=$Alias",
    "release.keyPassword=$KeyPassword"
)

if (-not (Test-Path $localProps)) {
    Copy-Item (Join-Path $root "local.properties.example") $localProps
}

$content = Get-Content $localProps -Raw
foreach ($line in $lines) {
    if ($line -eq "") { continue }
    $key = ($line -split "=", 2)[0]
    if ($content -match "(?m)^\s*$([regex]::Escape($key))=") {
        $content = $content -replace "(?m)^\s*$([regex]::Escape($key))=.*$", $line
    } else {
        $content = $content.TrimEnd() + "`n$line`n"
    }
}
Set-Content -Path $localProps -Value $content.TrimEnd() -NoNewline
Add-Content -Path $localProps -Value "`n"

Write-Host ""
Write-Host "Signing config written to local.properties"
Write-Host "Store password: $StorePassword"
Write-Host "Key alias:      $Alias"
Write-Host "Keep this keystore safe - you need it to upload updates to Google Play!"
